name: Nightly xmake test

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-tests:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/cheriot-platform/devcontainer:latest
      options: --user 1001
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build latest xmake
      run: |
        xmake update dev
        sudo apt remove -y xmake
        echo ~/.xmake/profile
        . ~/.xmake/profile
    - name: Build tests
      run: |
        pwd
        echo ~/.xmake/profile
        which xmake
        xmake --version
        cd tests
        xmake f --board=${{ matrix.board }} --sdk=/cheriot-tools/ ${{ matrix.build-flags }}
        xmake
    - name: Run tests
      run: |
        . ~/.xmake/profile
        xmake --version
        cd tests
        xmake run
